PATH:
    DATA:
        RAW:
            SURVEYS: /scratch/cs/corona/data/raw/surveys/
            POLAR: /scratch/cs/corona/data/raw/polar/
        PROCESSED: 
            SURVEYS: /scratch/cs/corona/data/processed/surveys/
            PA_ROUTINE: /scratch/cs/corona/data/processed/pa_routine/
            SLEEP: /scratch/cs/corona/data/processed/sleep/
    FIGURES: 
        PA_ROUTINE: /scratch/cs/corona/analysis/lnknguyen_analysis/figures/movement_routine/
        SLEEP: /scratch/cs/corona/analysis/lnknguyen_analysis/figures/sleep/

        
    