from yacs.config import CfgNode as CN

_C = CN()
_C.PATH = CN()
_C.PATH.DATA = CN()

_C.PATH.DATA.RAW = CN()
_C.PATH.DATA.RAW.SURVEYS = ""
_C.PATH.DATA.RAW.POLAR = ""

_C.PATH.DATA.PROCESSED = CN()
_C.PATH.DATA.PROCESSED.SURVEYS = ""
_C.PATH.DATA.PROCESSED.PA_ROUTINE = ""
_C.PATH.DATA.PROCESSED.SLEEP = ""

_C.PATH.FIGURES = CN()
_C.PATH.FIGURES.PA_ROUTINE = ""
_C.PATH.FIGURES.SLEEP = ""

cfg = _C
