groupby:
  tesserae:
    - user
    - date
  momo:
    - user
    - date
    - group
  globem:
    - user
    - date
    - wave

features:
  - activity_night
  - activity_morning
  - activity_afternoon
  - activity_evening
  - activity_allday
  - call_total_duration_night
  - call_total_duration_morning
  - call_total_duration_afternoon
  - call_total_duration_evening
  - call_total_duration_allday
  - screen_night
  - screen_morning
  - screen_afternoon
  - screen_evening
  - screen_allday
  - sleep_onset
  - sleep_offset
  - sleep_duration

# CLUSTERING SETTINGS
cluster_settings:
  tesserae:
    algorithm: gmm 
    split: false  # Apply clustering on data splits instead of the full dataset
    strategy: random  # Split strategy, only available if split is turned on
    group_col: null

    run_model_selection: False # Turn on this flag if model selection is required
    optimal_gmm_settings:
        n_components: 12
  momo:
    algorithm: gmm 
    split: false  
    strategy: random 
    group_col: null

    run_model_selection: 
    optimal_gmm_settings:
        n_components: 5
  globem:
    algorithm: gmm 
    split: false  
    strategy: group 
    group_col: wave

    run_model_selection: True
    optimal_gmm_settings:
        n_components: 5
        