
groupby:
  tesserae:
    - user
    - date
  dtu:
    - user
    - date
  momo:
    - user
    - date
    - group
  globem:
    - user
    - date
    - wave

# Sensors to extract
sensors:
  tesserae: ['screen', 'call', 'steps', 'sleep']
  globem: ['screen', 'call', 'steps', 'sleep']
  dtu: ['screen', 'sleep']
  
features:
  tesserae: [
    "activity_night",
    "activity_morning",
    "activity_afternoon",
    "activity_evening",
    "activity_allday",

    "screen_night",
    "screen_morning",
    "screen_afternoon",
    "screen_evening",
    "screen_allday",

    "sleep_onset",
    "sleep_offset",
    "sleep_duration"
]

  globem: [
    "activity_night",
    "activity_morning",
    "activity_afternoon",
    "activity_evening",
    "activity_allday",

]

  momo: [
    "activity_night",
    "activity_morning",
    "activity_afternoon",
    "activity_evening",
    "activity_allday",

    "screen_night",
    "screen_morning",
    "screen_afternoon",
    "screen_evening",
    "screen_allday",

    "sleep_onset",
    "sleep_offset",
    "sleep_duration"
]

  dtu: [
    "screen_night",
    "screen_morning",
    "screen_afternoon",
    "screen_evening",
    "screen_allday",

    "sleep_onset",
    "sleep_offset",
    "sleep_duration"
]


# CLUSTERING SETTINGS
cluster_settings:
  tesserae:
    algorithm: gmm 
    split: False  # Apply clustering on data splits instead of the full dataset
    strategy: random  # Split strategy, only available if split is turned on
    group_col: null # grouping col, used for splitting the dataset
    min_threshold: 14 # min number of records needed to be included in the analysis
    max_threshold: 365 # max number of records per user, if user has more observation than this, it will be capped at this threshold
    run_model_selection: False # Turn on this flag if model selection is required
    optimal_gmm_settings:
        n_components: 8
  momo:
    algorithm: gmm 
    split: False  
    strategy: random 
    group_col: null
    min_threshold: 14 # number of records needed to be included in the analysis
    max_threshold: 365
    run_model_selection: False
    optimal_gmm_settings:
        n_components: 8
        
  globem:
    algorithm: gmm 
    split: True  
    min_threshold: 14 # number of records needed to be included in the analysis
    max_threshold: 365
    strategy: group 
    group_col: wave

    run_model_selection: False
    optimal_gmm_settings:
        n_components: 14

  dtu:
    algorithm: gmm 
    split: False  
    min_threshold: 14 # number of records needed to be included in the analysis
    max_threshold: 365
    strategy: group 
    group_col: null

    run_model_selection: True
    optimal_gmm_settings: # This will be ignored if run_model_selection is set to True
        n_components: 8

# CLUSTERING SETTINGS
signature:
    ranked: 
        - ranked
        - unranked
    