groupby:
    tesserae:
        - user
        - date
    momo:
        - user
        - date
        - group
    globem:
        - user
        - date
        - wave

features:
    - activity_night
    - activity_morning
    - activity_afternoon
    - activity_evening
    - activity_allday
    - call_total_duration_night
    - call_total_duration_morning
    - call_total_duration_afternoon
    - call_total_duration_evening
    - call_total_duration_allday
    - screen_night
    - screen_morning
    - screen_afternoon
    - screen_evening
    - screen_allday
    - sleep_onset
    - sleep_offset
    - sleep_duration

### CLUSTERING ###
cluster_settings:

    tesserae:

        algorithm: gmm 
        split: True  # Apply clustering on data splits instead of the full dataset
        strategy: random # Split strategy, only available if split is turned on
        group_col: None
    momo:

        algorithm: gmm 
        split: True  
        strategy: random 
        group_col: None
    globem:

        algorithm: gmm 
        split: True  
        strategy: group 
        group_col: wave
