
groupby:
  tesserae:
    - user
    - date
  dtu:
    - user
    - date
  momo:
    - user
    - date
    - group
  globem:
    - user
    - date
    - wave

# Sensors to extract
sensors:
  tesserae: ['screen', 'call', 'steps', 'sleep']
  globem: ['screen', 'call', 'steps', 'sleep']
  dtu: ['screen', 'sleep']
  
features:
  - activity_night
  - activity_morning
  - activity_afternoon
  - activity_evening
  - activity_allday
  
  - screen_night
  - screen_morning
  - screen_afternoon
  - screen_evening
  - screen_allday
  
  - sleep_onset
  - sleep_offset
  - sleep_duration


# CLUSTERING SETTINGS
cluster_settings:
  tesserae:
    algorithm: gmm 
    split: False  # Apply clustering on data splits instead of the full dataset
    strategy: random  # Split strategy, only available if split is turned on
    group_col: null # grouping col, used for splitting the dataset
    threshold: 14 # number of records needed to be included in the analysis
    run_model_selection: False # Turn on this flag if model selection is required
    optimal_gmm_settings:
        n_components: 8
  momo:
    algorithm: gmm 
    split: False  
    strategy: random 
    group_col: null
    threshold: 14 # number of records needed to be included in the analysis
    run_model_selection: False
    optimal_gmm_settings:
        n_components: 8
        
  globem:
    algorithm: gmm 
    split: False  
    threshold: 14 # number of records needed to be included in the analysis
    strategy: group 
    group_col: wave

    run_model_selection: False
    optimal_gmm_settings:
        n_components: 8

  dtu:
    algorithm: gmm 
    split: False  
    threshold: 14 # number of records needed to be included in the analysis
    strategy: group 
    group_col: null

    run_model_selection: True
    optimal_gmm_settings: # This will be ignored if run_model_selection is set to True
        n_components: 8

# CLUSTERING SETTINGS
signature:
    ranked: 
        - ranked
        - unranked
    