rhythms:
  sensor: screen # possible sensor: screen, sms, call, loc
  time_window: 4H # time bin: 1H, 4H, 6H, 12H
  freq: daily # possible values: daily, weekly
  dist_func: cosine # possible values: cosine, jsd
  freeday: None # possbile values: True, False, None. If True, only include Sat/Sun. If False, only include Mon-Fri. If None, include every weekday.
  pilot: False # If True, run preprocess on pilot study
  feature: "empty" # Feature to compute rhythm for (e.g., call duration)
  
  path: "/m/cs/work/luongn1/momo_mood_analysis/data/processed/${rhythms.sensor}/${rhythms.sensor}_${rhythms.time_window}_${rhythms.freq}_freeday_${rhythms.freeday}.csv"
  dist_mat_path: "/m/cs/work/luongn1/momo_mood_analysis/data/dist_mat/${rhythms.sensor}_${rhythms.feature}_${rhythms.dist_func}_${rhythms.time_window}_${rhythms.freq}_freeday_${rhythms.freeday}.csv"


  pilot_path: "/m/cs/work/luongn1/momo_mood_analysis/data/processed/pilot/${rhythms.sensor}/${rhythms.sensor}_${rhythms.time_window}_${rhythms.freq}_freeday_${rhythms.freeday}.csv"
  pilot_dist_mat_path: "/m/cs/work/luongn1/momo_mood_analysis/data/dist_mat/pilot/${rhythms.sensor}_${rhythms.feature}_${rhythms.dist_func}_${rhythms.time_window}_${rhythms.freq}_freeday_${rhythms.freeday}.csv"
  