name: Figures sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@main
      - name: Fig sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            lnknguyen/digirhythm@main
          FILES: |
            workflow/notebooks/fig_1/=testfigs/
          TOKEN: ${{ secrets.ACTIONS }}

